project:
  type: website

website:
  description: "A blog on earth embeddings, earth observations, and novel ways to use all those sensors pointed at our earth."
  site-url: https://blog.mosaiks.org # you must change this appropriately for RSS feeds to work properly
  title: "The MOSAIKS Blog"
  favicon: favicon.png
  navbar:
    right:
      - text: "About"
        href: posts/welcome/index.qmd
      - text: "MOSAIKS.org"
        icon: house
        href: https://mosaiks.org
      - icon: github
        href: https://github.com/Global-Policy-Lab

format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css



